version: '3.3'
services:
  xbot:
    build:
      context: .
    container_name: "xbot"
    volumes:
      - .:/app  # Монтируем текущую директорию в контейнер
    command:  "sh start.inside.docker.sh"