version: '3.3'
services:
  xbot:
    build:
      context: .
    container_name: "xbot"
    volumes:
      - .:/app
    command:  "sh start.inside.docker.sh"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"