services:
  xbot:
    build:
      context: .
    container_name: "xbot"
    volumes:
      - .:/app  # Монтируем текущую директорию в контейнер
    command: "npm i && node --env-file=\".env\" xbot-worker.js"